services:
  geo_simulation:
    build: 
      context: .
    volumes:
      - .:/app
      - ./data:/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:10.0
    ports:
      - "2222:22"
    tty: true
    stdin_open: true